/**
 * AUTO-GENERATED by scripts/gen-brand-icons.ts — DO NOT EDIT BY HAND.
 * Regenerate: npx tsx scripts/gen-brand-icons.ts
 */

/** Shape of a lazily-loaded brand-path shard module. */
export interface BrandPathModule {
  BRAND_PATHS: Record<string, string>;
}

/**
 * Lazy per-shard loaders. Each value is a `() => import()` thunk, so webpack
 * code-splits every shard into its own async chunk — none are in the live
 * page bundle until a brand icon in that shard actually renders.
 */
export const BRAND_SHARD_LOADERS: Record<string, () => Promise<BrandPathModule>> = {
  "_digit": () => import("./_digit"),
  "a": () => import("./a"),
  "b": () => import("./b"),
  "c": () => import("./c"),
  "d": () => import("./d"),
  "e": () => import("./e"),
  "f": () => import("./f"),
  "g": () => import("./g"),
  "h": () => import("./h"),
  "i": () => import("./i"),
  "j": () => import("./j"),
  "k": () => import("./k"),
  "l": () => import("./l"),
  "m": () => import("./m"),
  "n": () => import("./n"),
  "o": () => import("./o"),
  "p": () => import("./p"),
  "q": () => import("./q"),
  "r": () => import("./r"),
  "s": () => import("./s"),
  "t": () => import("./t"),
  "u": () => import("./u"),
  "v": () => import("./v"),
  "w": () => import("./w"),
  "x": () => import("./x"),
  "y": () => import("./y"),
  "z": () => import("./z"),
};

/** Map a simple-icons slug to its shard key. Mirrors the generator buckets. */
export function brandShardKey(slug: string): string {
  const c = slug.charAt(0);
  return c >= '0' && c <= '9' ? '_digit' : c;
}
