/**
 * Dynamic Agent Registry — Single Source of Truth
 *
 * AUTO-GENERATED by scripts/generate-agent-registry.ts.
 * DO NOT EDIT BY HAND. Run `npx tsx scripts/generate-agent-registry.ts`
 * after adding or removing an agent file. CI runs the same script with
 * `--check` and fails the build on drift.
 *
 * Total agents: 72
 *   L1 (Master Orchestrator): 1
 *   L2 (Managers):            10
 *   L3 (Specialists):         57
 *   STANDALONE:               4
 *
 * Generated at: 2026-04-30T08:09:39.756Z
 *
 * @module lib/agents/agent-registry
 */

// ============================================================================
// TYPES
// ============================================================================

/** Agent tier in the swarm hierarchy */
export type AgentTier = 'L1' | 'L2' | 'L3' | 'STANDALONE';

/** Definition of an agent in the registry */
export interface AgentDefinition {
  id: string;
  name: string;
  role: string;
  tier: AgentTier;
  parentId: string | null;
  capabilities: string[];
}

// ============================================================================
// COMPLETE AGENT REGISTRY
// ============================================================================

/**
 * Authoritative registry of every agent in the platform.
 * Counts are computed from this array — never hardcoded elsewhere.
 */
export const AGENT_REGISTRY: AgentDefinition[] = [
  // =========================================================================
  // L1 - MASTER ORCHESTRATOR (1)
  // =========================================================================
  {
    id: 'MASTER_ORCHESTRATOR',
    name: "Swarm CEO",
    role: "Swarm CEO",
    tier: 'L1',
    parentId: null,
    capabilities: ['goal_processing', 'intent_classification', 'task_decomposition', 'saga_orchestration', 'command_dispatching', 'cross_domain_sync', 'swarm_monitoring', 'failure_compensation', 'status_aggregation', 'signal_coordination'],
  },

  // =========================================================================
  // L2 - ARCHITECT MANAGER (1)
  // =========================================================================
  {
    id: 'ARCHITECT_MANAGER',
    name: "Lead Architect",
    role: "Lead Architect",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['brand_dna_to_architecture', 'dynamic_specialist_orchestration', 'parallel_execution', 'graceful_degradation', 'intelligence_integration', 'sitemap_generation', 'funnel_flow_design', 'technical_brief_synthesis', 'signal_broadcast'],
  },

  // =========================================================================
  // L2 - BUILDER MANAGER (1)
  // =========================================================================
  {
    id: 'BUILDER_MANAGER',
    name: "Builder Manager",
    role: "Builder Manager",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['blueprint_to_deployment', 'dynamic_specialist_orchestration', 'parallel_execution', 'graceful_degradation', 'pixel_injection', 'script_management', 'page_assembly', 'asset_coordination', 'state_machine_tracking', 'signal_broadcast'],
  },

  // =========================================================================
  // L2 - COMMERCE MANAGER (1)
  // =========================================================================
  {
    id: 'COMMERCE_MANAGER',
    name: "Commerce Manager",
    role: "Commerce Manager",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['checkout_orchestration', 'catalog_operations', 'revenue_reporting', 'inventory_coordination', 'pricing_strategy'],
  },

  // =========================================================================
  // L2 - CONTENT MANAGER (1)
  // =========================================================================
  {
    id: 'CONTENT_MANAGER',
    name: "Content Manager",
    role: "Content Manager",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['content_strategy', 'copywriting_coordination', 'editorial_calendar', 'visual_asset_coordination', 'video_production_planning', 'seo_content_integration', 'brand_voice_enforcement', 'multi_modal_synthesis', 'content_validation', 'soundtrack_planning', 'podcast_planning'],
  },

  // =========================================================================
  // L2 - INTELLIGENCE MANAGER (1)
  // =========================================================================
  {
    id: 'INTELLIGENCE_MANAGER',
    name: "Intelligence Manager",
    role: "Intelligence Manager",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['competitor_analysis_delegation', 'sentiment_analysis_delegation', 'technographic_analysis_delegation', 'trend_analysis_delegation', 'company_profiling_delegation', 'multi_specialist_orchestration', 'parallel_execution', 'graceful_degradation', 'intelligence_synthesis', 'market_intelligence_aggregation'],
  },

  // =========================================================================
  // L2 - MARKETING MANAGER (1)
  // =========================================================================
  {
    id: 'MARKETING_MANAGER',
    name: "Marketing Manager",
    role: "Marketing Manager",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['campaign_goal_parsing', 'intent_detection', 'dynamic_specialist_resolution', 'brand_dna_integration', 'seo_social_feedback_loop', 'multi_specialist_coordination', 'cross_platform_campaigns', 'budget_allocation', 'campaign_brief_synthesis'],
  },

  // =========================================================================
  // L2 - OPERATIONS MANAGER (1)
  // =========================================================================
  {
    id: 'OPERATIONS_MANAGER',
    name: "Operations Manager",
    role: "Operations Manager",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['meeting_creation', 'meeting_rescheduling', 'meeting_cancellation', 'calendar_integrity', 'availability_enforcement', 'attendee_validation'],
  },

  // =========================================================================
  // L2 - OUTREACH MANAGER (1)
  // =========================================================================
  {
    id: 'OUTREACH_MANAGER',
    name: "Outreach Manager",
    role: "Outreach Manager",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['omnichannel_orchestration', 'sequence_execution', 'sentiment_aware_routing', 'dnc_compliance', 'throttle_control', 'template_injection', 'channel_escalation', 'engagement_tracking', 'multi_specialist_coordination'],
  },

  // =========================================================================
  // L2 - SALES MANAGER (1)
  // =========================================================================
  {
    id: 'REVENUE_DIRECTOR',
    name: "Revenue Director",
    role: "Revenue Director",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['lead_pipeline_management', 'transition_rules_engine', 'bant_evaluation', 'intelligence_assessment', 'engagement_monitoring', 'time_based_enforcement', 'specialist_delegation', 'readiness_scoring', 'golden_master_orchestration', 'persona_tuning', 'revenue_brief_synthesis', 'objection_library_synthesis', 'cross_agent_signal_sharing', 'win_loss_feedback_loops'],
  },

  // =========================================================================
  // L2 - TRUST MANAGER (1)
  // =========================================================================
  {
    id: 'REPUTATION_MANAGER',
    name: "Reputation Manager",
    role: "Reputation Manager",
    tier: 'L2',
    parentId: 'MASTER_ORCHESTRATOR',
    capabilities: ['sentiment_monitoring', 'crisis_detection', 'response_strategy_determination', 'brand_health_tracking', 'review_coordination', 'gmb_coordination', 'escalation_management', 'multi_channel_reputation', 'automated_review_solicitation', 'ai_response_generation', 'trust_score_synthesis', 'review_to_revenue_loop'],
  },

  // =========================================================================
  // L3 - ARCHITECT SPECIALISTS (3)
  // =========================================================================
  {
    id: 'COPY_STRATEGIST',
    name: "Copy Strategist",
    role: "Copy Strategist",
    tier: 'L3',
    parentId: 'ARCHITECT_MANAGER',
    capabilities: ['generate_copy'],
  },
  {
    id: 'FUNNEL_STRATEGIST',
    name: "Funnel Strategist",
    role: "Funnel Strategist",
    tier: 'L3',
    parentId: 'ARCHITECT_MANAGER',
    capabilities: ['analyze_funnel'],
  },
  {
    id: 'UX_UI_STRATEGIST',
    name: "UX/UI Strategist",
    role: "UX/UI Strategist",
    tier: 'L3',
    parentId: 'ARCHITECT_MANAGER',
    capabilities: ['design_page'],
  },

  // =========================================================================
  // L3 - BUILDER SPECIALISTS (4)
  // =========================================================================
  {
    id: 'ASSET_GENERATOR',
    name: "Asset Generator",
    role: "Asset Generator",
    tier: 'L3',
    parentId: 'CONTENT_MANAGER',
    capabilities: ['generate_asset_package'],
  },
  {
    id: 'FUNNEL_ENGINEER',
    name: "Funnel Engineer",
    role: "Funnel Engineer",
    tier: 'L3',
    parentId: 'BUILDER_MANAGER',
    capabilities: ['design_funnel'],
  },
  {
    id: 'UX_UI_ARCHITECT',
    name: "UX/UI Architect",
    role: "UX/UI Architect",
    tier: 'L3',
    parentId: 'BUILDER_MANAGER',
    capabilities: ['generate_design_system'],
  },
  {
    id: 'WORKFLOW_OPTIMIZER',
    name: "Workflow Optimizer",
    role: "Workflow Optimizer",
    tier: 'L3',
    parentId: 'BUILDER_MANAGER',
    capabilities: ['compose_workflow'],
  },

  // =========================================================================
  // L3 - COMMERCE SPECIALISTS (4)
  // =========================================================================
  {
    id: 'CATALOG_MANAGER',
    name: "Catalog Manager",
    role: "Catalog Manager",
    tier: 'L3',
    parentId: 'COMMERCE_MANAGER',
    capabilities: ['fetch_products', 'manage_catalog', 'variant_management', 'price_management', 'category_organization', 'product_search'],
  },
  {
    id: 'INVENTORY_MANAGER',
    name: "Inventory Manager",
    role: "Inventory Manager",
    tier: 'L3',
    parentId: 'COMMERCE_MANAGER',
    capabilities: ['stock_analysis', 'demand_forecast', 'reorder_alerts', 'turnover_analysis'],
  },
  {
    id: 'PAYMENT_SPECIALIST',
    name: "Payment Specialist",
    role: "Payment Specialist",
    tier: 'L3',
    parentId: 'COMMERCE_MANAGER',
    capabilities: ['initialize_checkout', 'create_payment_intent', 'validate_payment', 'process_refund', 'webhook_coordination', 'checkout_session_status'],
  },
  {
    id: 'PRICING_STRATEGIST',
    name: "Pricing Strategist",
    role: "Pricing Strategist",
    tier: 'L3',
    parentId: 'COMMERCE_MANAGER',
    capabilities: ['process_payment', 'validate_pricing', 'apply_discount', 'calculate_total', 'dynamic_pricing', 'competitor_price_tracking', 'margin_optimization', 'discount_strategy'],
  },

  // =========================================================================
  // L3 - CONTENT SPECIALISTS (6)
  // =========================================================================
  {
    id: 'BLOG_WRITER',
    name: "Blog Writer",
    role: "Blog Writer",
    tier: 'L3',
    parentId: 'CONTENT_MANAGER',
    capabilities: ['write_blog_post', 'outline_blog_post'],
  },
  {
    id: 'CALENDAR_COORDINATOR',
    name: "Calendar Coordinator",
    role: "Calendar Coordinator",
    tier: 'L3',
    parentId: 'CONTENT_MANAGER',
    capabilities: ['plan_calendar'],
  },
  {
    id: 'COPYWRITER',
    name: "Copywriter",
    role: "Copywriter",
    tier: 'L3',
    parentId: 'CONTENT_MANAGER',
    capabilities: ['generate_page_copy', 'generate_proposal', 'generate_email_sequence'],
  },
  {
    id: 'MUSIC_PLANNER',
    name: "Music/Soundtrack Planner",
    role: "Music/Soundtrack Planner",
    tier: 'L3',
    parentId: 'CONTENT_MANAGER',
    capabilities: ['plan_soundtrack', 'recommend_music_style'],
  },
  {
    id: 'PODCAST_SPECIALIST',
    name: "Podcast Specialist",
    role: "Podcast Specialist",
    tier: 'L3',
    parentId: 'CONTENT_MANAGER',
    capabilities: ['plan_episode', 'write_show_notes'],
  },
  {
    id: 'VIDEO_SPECIALIST',
    name: "Video Specialist",
    role: "Video Specialist",
    tier: 'L3',
    parentId: 'CONTENT_MANAGER',
    capabilities: ['script_to_storyboard'],
  },

  // =========================================================================
  // L3 - GROWTH-STRATEGIST SPECIALISTS (1)
  // =========================================================================
  {
    id: 'GROWTH_STRATEGIST',
    name: "Growth Strategist",
    role: "Growth Strategist",
    tier: 'L3',
    parentId: null,
    capabilities: ['business_review', 'seo_strategy', 'ad_spend_analysis', 'demographic_targeting', 'channel_attribution', 'strategic_briefing', 'cross_domain_synthesis'],
  },

  // =========================================================================
  // L3 - INTELLIGENCE SPECIALISTS (5)
  // =========================================================================
  {
    id: 'COMPETITOR_RESEARCHER',
    name: "Competitor Researcher",
    role: "Competitor Researcher",
    tier: 'L3',
    parentId: 'INTELLIGENCE_MANAGER',
    capabilities: ['competitor_discovery', 'seo_analysis', 'market_positioning', 'feature_comparison', 'gap_analysis', 'llm_market_synthesis'],
  },
  {
    id: 'SCRAPER_SPECIALIST',
    name: "Scraper Specialist",
    role: "Scraper Specialist",
    tier: 'L3',
    parentId: 'INTELLIGENCE_MANAGER',
    capabilities: ['website_scraping', 'content_extraction', 'contact_discovery', 'business_signal_detection', 'llm_analysis', 'structured_output'],
  },
  {
    id: 'SENTIMENT_ANALYST',
    name: "Sentiment Analyst",
    role: "Sentiment Analyst",
    tier: 'L3',
    parentId: 'INTELLIGENCE_MANAGER',
    capabilities: ['sentiment_analysis', 'emotion_detection', 'brand_sentiment', 'crisis_detection', 'trend_analysis', 'aspect_extraction'],
  },
  {
    id: 'TECHNOGRAPHIC_SCOUT',
    name: "Technographic Scout",
    role: "Technographic Scout",
    tier: 'L3',
    parentId: 'INTELLIGENCE_MANAGER',
    capabilities: ['tech_stack_detection', 'platform_identification', 'analytics_detection', 'pixel_detection', 'integration_discovery', 'llm_tech_interpretation'],
  },
  {
    id: 'TREND_SCOUT',
    name: "Trend Scout",
    role: "Trend Scout",
    tier: 'L3',
    parentId: 'INTELLIGENCE_MANAGER',
    capabilities: ['market_signal_detection', 'competitor_tracking', 'industry_analysis', 'trend_forecasting', 'pivot_triggering', 'signal_aggregation', 'urgency_classification', 'llm_signal_synthesis'],
  },

  // =========================================================================
  // L3 - MARKETING SPECIALISTS (19)
  // =========================================================================
  {
    id: 'BLUESKY_EXPERT',
    name: "Bluesky Expert",
    role: "Bluesky Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content', 'compose_dm_reply'],
  },
  {
    id: 'DISCORD_EXPERT',
    name: "Discord Expert",
    role: "Discord Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content', 'compose_dm_reply'],
  },
  {
    id: 'FACEBOOK_ADS_EXPERT',
    name: "Facebook Ads Expert",
    role: "Facebook Ads Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content', 'compose_dm_reply'],
  },
  {
    id: 'GOOGLE_BUSINESS_EXPERT',
    name: "Google Business Expert",
    role: "Google Business Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },
  {
    id: 'GROWTH_ANALYST',
    name: "Growth Analyst",
    role: "Growth Analyst",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },
  {
    id: 'INSTAGRAM_EXPERT',
    name: "Instagram Expert",
    role: "Instagram Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content', 'compose_dm_reply'],
  },
  {
    id: 'LINKEDIN_EXPERT',
    name: "LinkedIn Expert",
    role: "LinkedIn Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content', 'compose_dm_reply'],
  },
  {
    id: 'MASTODON_EXPERT',
    name: "Mastodon Expert",
    role: "Mastodon Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content', 'compose_dm_reply'],
  },
  {
    id: 'PAID_ADS_SPECIALIST',
    name: "Paid Advertising Specialist",
    role: "Paid Advertising Specialist",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['plan_campaign', 'optimize_campaign', 'analyze_ad_performance'],
  },
  {
    id: 'PINTEREST_EXPERT',
    name: "Pinterest Expert",
    role: "Pinterest Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content', 'compose_dm_reply'],
  },
  {
    id: 'REDDIT_EXPERT',
    name: "Reddit Expert",
    role: "Reddit Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },
  {
    id: 'SEO_EXPERT',
    name: "SEO Expert",
    role: "SEO Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['keyword_research', 'domain_analysis'],
  },
  {
    id: 'TELEGRAM_EXPERT',
    name: "Telegram Expert",
    role: "Telegram Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },
  {
    id: 'THREADS_EXPERT',
    name: "Threads Expert",
    role: "Threads Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },
  {
    id: 'TIKTOK_EXPERT',
    name: "TikTok Expert",
    role: "TikTok Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },
  {
    id: 'TWITCH_EXPERT',
    name: "Twitch Expert",
    role: "Twitch Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },
  {
    id: 'TWITTER_X_EXPERT',
    name: "Twitter/X Expert",
    role: "Twitter/X Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content', 'compose_dm_reply'],
  },
  {
    id: 'WHATSAPP_BUSINESS_EXPERT',
    name: "WhatsApp Business Expert",
    role: "WhatsApp Business Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },
  {
    id: 'YOUTUBE_EXPERT',
    name: "YouTube Expert",
    role: "YouTube Expert",
    tier: 'L3',
    parentId: 'MARKETING_MANAGER',
    capabilities: ['generate_content'],
  },

  // =========================================================================
  // L3 - OPERATIONS SPECIALISTS (1)
  // =========================================================================
  {
    id: 'SCHEDULING_SPECIALIST',
    name: "Scheduling Specialist",
    role: "Scheduling Specialist",
    tier: 'L3',
    parentId: 'OPERATIONS_MANAGER',
    capabilities: ['create_meeting', 'reschedule_meeting', 'cancel_meeting'],
  },

  // =========================================================================
  // L3 - OUTREACH SPECIALISTS (3)
  // =========================================================================
  {
    id: 'EMAIL_SPECIALIST',
    name: "Email Specialist",
    role: "Email Specialist",
    tier: 'L3',
    parentId: 'OUTREACH_MANAGER',
    capabilities: ['compose_email'],
  },
  {
    id: 'SMS_SPECIALIST',
    name: "SMS Specialist",
    role: "SMS Specialist",
    tier: 'L3',
    parentId: 'OUTREACH_MANAGER',
    capabilities: ['compose_sms'],
  },
  {
    id: 'VOICE_AI_SPECIALIST',
    name: "Voice Service (Twilio dispatcher)",
    role: "Voice Service (Twilio dispatcher)",
    tier: 'L3',
    parentId: 'OUTREACH_MANAGER',
    capabilities: ['make_call', 'get_call_status', 'end_call', 'send_dtmf', 'transfer_call', 'get_recording', 'call_tracking'],
  },

  // =========================================================================
  // L3 - PROMPT-ENGINEER SPECIALISTS (1)
  // =========================================================================
  {
    id: 'PROMPT_ENGINEER',
    name: "Prompt Engineer",
    role: "Prompt Engineer",
    tier: 'L3',
    parentId: null,
    capabilities: ['prompt_editing', 'correction_interpretation', 'surgical_rewrite'],
  },

  // =========================================================================
  // L3 - SALES SPECIALISTS (5)
  // =========================================================================
  {
    id: 'DEAL_CLOSER',
    name: "Deal Closer",
    role: "Deal Closer",
    tier: 'L3',
    parentId: 'REVENUE_DIRECTOR',
    capabilities: ['closing_strategy', 'readiness_assessment', 'personalized_scripting', 'contract_drafting', 'closing_email', 'objection_preemption'],
  },
  {
    id: 'MERCHANDISER',
    name: "Merchandiser",
    role: "Merchandiser",
    tier: 'L3',
    parentId: 'REVENUE_DIRECTOR',
    capabilities: ['nudge_evaluation', 'interaction_scoring', 'coupon_generation', 'roi_analysis', 'constraint_validation'],
  },
  {
    id: 'OBJ_HANDLER',
    name: "Objection Handler",
    role: "Objection Handler",
    tier: 'L3',
    parentId: 'REVENUE_DIRECTOR',
    capabilities: ['objection_classification', 'rebuttal_generation', 'reframing_strategy', 'value_prop_mapping', 'escalation_advice'],
  },
  {
    id: 'OUTREACH_SPECIALIST',
    name: "Sales Outreach Specialist",
    role: "Sales Outreach Specialist",
    tier: 'L3',
    parentId: 'REVENUE_DIRECTOR',
    capabilities: ['framework_selection', 'first_touch_message', 'sequence_planning', 'personalization', 'competitor_displacement', 'trigger_event_outreach'],
  },
  {
    id: 'LEAD_QUALIFIER',
    name: "Lead Qualifier",
    role: "Lead Qualifier",
    tier: 'L3',
    parentId: 'REVENUE_DIRECTOR',
    capabilities: ['bant_scoring', 'lead_qualification', 'icp_alignment', 'market_intelligence_integration', 'qualification_reporting'],
  },

  // =========================================================================
  // L3 - SALES-CHAT SPECIALISTS (1)
  // =========================================================================
  {
    id: 'AI_CHAT_SALES_AGENT',
    name: "AI Chat Sales Agent",
    role: "AI Chat Sales Agent",
    tier: 'L3',
    parentId: null,
    capabilities: ['lead_qualification', 'product_questions', 'trial_guidance', 'demo_scheduling', 'objection_handling', 'facebook_messenger', 'website_chat'],
  },

  // =========================================================================
  // L3 - TRUST SPECIALISTS (4)
  // =========================================================================
  {
    id: 'CASE_STUDY',
    name: "Case Study Builder",
    role: "Case Study Builder",
    tier: 'L3',
    parentId: 'REPUTATION_MANAGER',
    capabilities: ['narrative_generation', 'before_after_structure', 'seo_optimization', 'json_ld_schema', 'metric_visualization'],
  },
  {
    id: 'GMB_SPECIALIST',
    name: "GMB Specialist",
    role: "GMB Specialist",
    tier: 'L3',
    parentId: 'REPUTATION_MANAGER',
    capabilities: ['local_seo', 'gmb_posting', 'map_pack_optimization', 'nap_audit', 'local_competitor_analysis'],
  },
  {
    id: 'REV_MGR',
    name: "Review Manager",
    role: "Review Manager",
    tier: 'L3',
    parentId: 'REPUTATION_MANAGER',
    capabilities: ['bulk_sentiment_analysis', 'review_campaign_generation', 'trend_reporting', 'brand_voice_alignment', 'topic_extraction'],
  },
  {
    id: 'REVIEW_SPECIALIST',
    name: "Review Specialist",
    role: "Review Specialist",
    tier: 'L3',
    parentId: 'REPUTATION_MANAGER',
    capabilities: ['review_response', 'sentiment_analysis', 'escalation_decision', 'platform_adaptation', 'follow_up_planning'],
  },

  // =========================================================================
  // STANDALONE (4)
  // =========================================================================
  {
    id: 'JASPER',
    name: "Jasper",
    role: "Internal AI Assistant & Swarm Commander",
    tier: 'STANDALONE',
    parentId: null,
    capabilities: ['Swarm Command', 'Executive Briefings', 'System Orchestration', 'Employee Management', 'Strategic Guidance'],
  },
  {
    id: 'VOICE_AGENT_HANDLER',
    name: "Voice Agent",
    role: "Voice AI Agent",
    tier: 'STANDALONE',
    parentId: null,
    capabilities: ['AI Phone Conversations', 'Lead Qualification (Voice)', 'Deal Closing (Voice)', 'Warm Transfer'],
  },
  {
    id: 'AUTONOMOUS_POSTING_AGENT',
    name: "Autonomous Posting Agent",
    role: "Social Media Automation",
    tier: 'STANDALONE',
    parentId: null,
    capabilities: ['LinkedIn Posting', 'Twitter Posting', 'Content Scheduling', 'Queue Management'],
  },
  {
    id: 'CHAT_SESSION_SERVICE',
    name: "Chat Session Service",
    role: "Agent Infrastructure",
    tier: 'STANDALONE',
    parentId: null,
    capabilities: ['Session Management', 'Conversation Monitoring', 'Agent Instance Lifecycle', 'Golden Master Spawning'],
  },
];

// ============================================================================
// COMPUTED STATS (calculated once at module init)
// ============================================================================

const l1Agents = AGENT_REGISTRY.filter(a => a.tier === 'L1');
const l2Agents = AGENT_REGISTRY.filter(a => a.tier === 'L2');
const l3Agents = AGENT_REGISTRY.filter(a => a.tier === 'L3');
const standaloneAgents = AGENT_REGISTRY.filter(a => a.tier === 'STANDALONE');
const swarmAgents = AGENT_REGISTRY.filter(a => a.tier !== 'STANDALONE');

export const AGENT_COUNTS = {
  total: AGENT_REGISTRY.length,
  swarm: swarmAgents.length,
  L1: l1Agents.length,
  L2: l2Agents.length,
  L3: l3Agents.length,
  STANDALONE: standaloneAgents.length,
} as const;

/** Display names for L2 manager domains */
const DOMAIN_DISPLAY_NAMES: Record<string, string> = {
  INTELLIGENCE_MANAGER: 'Intelligence',
  MARKETING_MANAGER: 'Marketing',
  BUILDER_MANAGER: 'Builder',
  COMMERCE_MANAGER: 'Commerce',
  OUTREACH_MANAGER: 'Outreach',
  CONTENT_MANAGER: 'Content',
  ARCHITECT_MANAGER: 'Architecture',
  REVENUE_DIRECTOR: 'Revenue',
  REPUTATION_MANAGER: 'Reputation',
  OPERATIONS_MANAGER: 'Operations',
};

// ============================================================================
// GETTER FUNCTIONS
// ============================================================================

/** Total number of agents (all tiers) */
export function getAgentCount(): number {
  return AGENT_REGISTRY.length;
}

/** Number of agents in the swarm hierarchy (L1 + L2 + L3, excludes standalone) */
export function getSwarmAgentCount(): number {
  return swarmAgents.length;
}

/** Number of standalone agents */
export function getStandaloneCount(): number {
  return standaloneAgents.length;
}

/** Number of L2 managers (also = number of domains) */
export function getManagerCount(): number {
  return l2Agents.length;
}

/** Number of L3 specialists */
export function getSpecialistCount(): number {
  return l3Agents.length;
}

/** Number of L1 orchestrators */
export function getOrchestratorCount(): number {
  return l1Agents.length;
}

/** Number of domains (= number of L2 managers) */
export function getDomainCount(): number {
  return l2Agents.length;
}

/** Get all agents of a specific tier */
export function getAgentsByTier(tier: AgentTier): AgentDefinition[] {
  return AGENT_REGISTRY.filter((a) => a.tier === tier);
}

/** Get a specific agent by ID */
export function getAgentById(id: string): AgentDefinition | undefined {
  return AGENT_REGISTRY.find((a) => a.id === id);
}

/** Get all agents whose parent is the given id */
export function getAgentsByParent(parentId: string): AgentDefinition[] {
  return AGENT_REGISTRY.filter((a) => a.parentId === parentId);
}

/** Get all specialists under a specific manager */
export function getSpecialistsByManager(managerId: string): AgentDefinition[] {
  return AGENT_REGISTRY.filter((a) => a.tier === 'L3' && a.parentId === managerId);
}

/** Get display names for all domains (derived from L2 managers) */
export function getDomainNames(): string[] {
  return l2Agents.map((m) => DOMAIN_DISPLAY_NAMES[m.id] ?? m.name);
}

/**
 * Human-readable swarm summary.
 * Example: "70-agent AI swarm across 9 domains"
 */
export function getSwarmSummary(): string {
  return `${getAgentCount()}-agent AI swarm across ${getDomainCount()} domains`;
}

/**
 * Human-readable hierarchy breakdown.
 * Example: "1 Master Orchestrator + 9 Domain Managers + 56 Specialists + 4 Standalone"
 */
export function getHierarchySummary(): string {
  return `${l1Agents.length} Master Orchestrator + ${l2Agents.length} Domain Managers + ${l3Agents.length} Specialists + ${standaloneAgents.length} Standalone`;
}

/** Full stats breakdown object */
export function getAgentRegistryStats(): {
  total: number;
  orchestrators: number;
  managers: number;
  specialists: number;
  standalone: number;
  swarm: number;
  domains: number;
} {
  return {
    total: AGENT_REGISTRY.length,
    orchestrators: l1Agents.length,
    managers: l2Agents.length,
    specialists: l3Agents.length,
    standalone: standaloneAgents.length,
    swarm: swarmAgents.length,
    domains: l2Agents.length,
  };
}

/**
 * Build the hardcoded blueprint agent section dynamically.
 * Used by jasper-tools.ts getHardcodedBlueprintSection().
 */
export function buildAgentBlueprintSection(): string {
  const lines: string[] = [];
  lines.push(`${getAgentCount()} TOTAL AGENTS: ${getHierarchySummary()}`);
  lines.push('');
  lines.push(`MASTER ORCHESTRATOR (L1): ${l1Agents[0]?.role ?? 'Swarm CEO'} — command dispatch, saga workflows, intent-based domain routing`);
  lines.push('');
  lines.push(`${l2Agents.length} DOMAIN MANAGERS (L2):`);

  l2Agents.forEach((manager, idx) => {
    const specs = getSpecialistsByManager(manager.id);
    const specNames = specs.map((s) => s.name).join(', ');
    lines.push(`${idx + 1}. ${manager.name} — ${specs.length} specialists (${specNames})`);
  });

  lines.push('');
  lines.push(`STANDALONE AGENTS (${standaloneAgents.length}):`);
  standaloneAgents.forEach((agent) => {
    const capSummary = agent.capabilities.slice(0, 2).join(', ');
    lines.push(`- ${agent.name} (${agent.role} — ${capSummary})`);
  });

  return lines.join('\n');
}
