/**
 * AI Video Generation Engine
 *
 * Industry-leading video generation system featuring:
 * - Director Service: Brand DNA + Trends → Master Storyboard
 * - Multi-Model Picker: Intelligent provider routing (Veo/Runway/Kling)
 * - Stitcher Service: TTS layering, BPM-aware music ducking, LUT filtering
 * - Style Guide Integrator: Site-mimicry for brand visual consistency
 *
 * @module video/engine
 */

// ============================================================================
// TYPES
// ============================================================================

export type {
  // Shot & Camera
  ShotType,
  CameraMotion,
  TransitionType,

  // Providers
  VideoGenerationProvider,
  ProviderCapabilities,

  // Storyboard
  MasterStoryboard,
  StoryboardScene,
  StoryboardShot,
  BrandDNASnapshot,
  StoryboardStatus,
  ShotGenerationStatus,

  // Visual Prompts
  VisualPrompt,
  LightingStyle,
  TextOverlay,

  // Audio
  AudioConfiguration,
  AudioTimingMarker,
  AudioMarkerType,
  VoiceoverScript,
  VoiceoverSegment,
  DuckingConfig,
  SoundEffect,
  AudioTrack,

  // Visual Style
  VisualStyleConfig,

  // Trend Reports
  TrendReport,
  VisualTrend,
  AudienceTrend,
  PlatformTrend,
  CompetitorInsight,

  // Site Mimicry
  SiteMimicryStyleGuide,

  // Post-Production
  PostProductionJob,
  PostProductionStatus,
  PostProductionError,
  GeneratedClip,

  // Queue & Routing
  GenerationQueueItem,
  ProviderRoutingDecision,

  // Director
  DirectorRequest,
  DirectorResponse,
} from './types';

// ============================================================================
// DIRECTOR SERVICE
// ============================================================================

export {
  DirectorService,
  directorService,
  generateStoryboard,
} from './director-service';

// ============================================================================
// MULTI-MODEL PICKER
// ============================================================================

export {
  MultiModelPicker,
  multiModelPicker,
  selectProvider,
  routeStoryboard,
  getProviderCapabilities,
  estimateStoryboardCost,
  PROVIDER_REGISTRY,
} from './multi-model-picker';

export type {
  PickerConfig,
  RoutingContext,
} from './multi-model-picker';

// ============================================================================
// STITCHER SERVICE
// ============================================================================

export {
  StitcherService,
  stitcherService,
  createPostProductionJob,
  processPostProduction,
  getPostProductionStatus,
  getLUTPresets,
} from './stitcher-service';

// ============================================================================
// STYLE GUIDE INTEGRATOR
// ============================================================================

export {
  StyleGuideIntegrator,
  styleGuideIntegrator,
  extractStyleGuide,
  convertToVisualStyleConfig,
  generatePromptModifiers,
  enhancePromptWithStyleGuide,
  recommendCameraSettings,
} from './style-guide-integrator';

export type {
  CrawledWebsiteData,
  ProcessedStyleGuide,
  PromptModifiers,
  CameraRecommendations,
} from './style-guide-integrator';

// ============================================================================
// CONVENIENCE FUNCTIONS
// ============================================================================

import { DirectorService } from './director-service';
import { MultiModelPicker } from './multi-model-picker';
import { StitcherService } from './stitcher-service';
import { StyleGuideIntegrator } from './style-guide-integrator';
import type {
  DirectorRequest,
  DirectorResponse,
  MasterStoryboard,
  GeneratedClip,
  PostProductionJob,
  SiteMimicryStyleGuide,
} from './types';

/**
 * Complete video generation pipeline
 *
 * Orchestrates the full workflow from brand DNA to final rendered video:
 * 1. Director creates storyboard from brand DNA and brief
 * 2. Multi-Model Picker routes shots to optimal providers
 * 3. (External) Video clips are generated by providers
 * 4. Stitcher assembles final video with audio and effects
 */
export async function generateVideo(
  request: DirectorRequest,
  styleGuide?: SiteMimicryStyleGuide
): Promise<{
  storyboard: MasterStoryboard;
  generationQueue: import('./types').GenerationQueueItem[];
  estimatedCost: DirectorResponse['estimatedCost'];
}> {
  const director = DirectorService.getInstance();
  const picker = MultiModelPicker.getInstance();
  const styleIntegrator = StyleGuideIntegrator.getInstance();

  // Enhance request with style guide if provided
  let enhancedRequest = request;
  if (styleGuide) {
    enhancedRequest = {
      ...request,
      styleGuide,
      brandDNA: styleIntegrator.createVideoOptimizedBrandDNA(
        request.brandDNA,
        styleGuide
      ),
    };
  }

  // Generate storyboard
  const directorResponse = await director.generateStoryboard(enhancedRequest);

  // Get all shots from storyboard
  const allShots = directorResponse.storyboard.scenes.flatMap(scene => scene.shots);

  // Route shots to providers
  const generationQueue = picker.routeStoryboard(
    request.organizationId,
    directorResponse.storyboard.id,
    allShots,
    request.constraints.aspectRatio,
    request.constraints.resolution,
    {
      preferQualityOverCost: true,
      minQuality: 'high',
    }
  );

  return {
    storyboard: directorResponse.storyboard,
    generationQueue,
    estimatedCost: directorResponse.estimatedCost,
  };
}

/**
 * Process generated clips into final video
 */
export async function finalizeVideo(
  storyboard: MasterStoryboard,
  generatedClips: GeneratedClip[]
): Promise<PostProductionJob> {
  const stitcher = StitcherService.getInstance();

  // Create post-production job
  const job = await stitcher.createJob(storyboard, generatedClips);

  // Process the job
  return stitcher.processJob(job, storyboard);
}

/**
 * Get video engine status and health
 */
export function getEngineStatus(): {
  providerHealth: Map<import('./types').VideoGenerationProvider, {
    status: string;
    successRate: number;
  }>;
  activeJobs: number;
} {
  const picker = MultiModelPicker.getInstance();
  const stitcher = StitcherService.getInstance();

  const healthMap = picker.getProviderHealthStatus();
  const providerHealth = new Map<import('./types').VideoGenerationProvider, { status: string; successRate: number }>();

  for (const [provider, health] of healthMap) {
    providerHealth.set(provider, {
      status: health.status,
      successRate: health.totalRequests > 0
        ? health.successCount / health.totalRequests
        : 1,
    });
  }

  return {
    providerHealth,
    activeJobs: 0, // Would need to track this in stitcher
  };
}
