/**
 * gen-brand-icons.ts
 * -----------------------------------------------------------------------------
 * One-off generator for the website-builder "Brands" icon set, sourced from the
 * installed `simple-icons` package (v16.x).
 *
 * Run:  npx tsx scripts/gen-brand-icons.ts
 *
 * Outputs (all under src/lib/website-builder/):
 *   1. brand-icons.ts ................ LIGHT metadata list `BRAND_ICONS`
 *      ({ slug, title, hex } only — NO svg path data, so the picker list and any
 *      module that imports it stays small). Used by IconPicker.
 *   2. brand-icon-paths/<bucket>.ts .. sharded `BRAND_PATHS` maps (slug -> svg
 *      path), bucketed by the first character of the slug. These are the HEAVY
 *      files (~4.4 MB total across all brands) and are ONLY ever pulled in via
 *      lazy dynamic import(), never statically — so they are code-split per
 *      shard and never land in the published page bundle.
 *   3. brand-icon-paths/loaders.ts ... `BRAND_SHARD_LOADERS` (a tiny map of
 *      `() => import('./<bucket>')` thunks) + `brandShardKey(slug)`. This is the
 *      only brand-paths module that is statically imported (by Icon.tsx); it is
 *      lightweight (just lazy thunks) and triggers the per-shard split.
 *
 * Re-run this after upgrading `simple-icons` to refresh the brand set.
 */

/* eslint-disable */
const fs = require('fs');
const path = require('path');

// Metadata (title/slug/hex/...) — no path data here.
const iconsData = require('simple-icons/icons.json') as Array<{
  title: string;
  slug: string;
  hex: string;
}>;
// Full barrel (each export carries `.path`) + slug -> export-name helper.
const si = require('simple-icons') as Record<string, { path: string } | undefined>;
const { slugToVariableName } = require('simple-icons/sdk') as {
  slugToVariableName: (slug: string) => string;
};

const OUT_DIR = path.join(__dirname, '..', 'src', 'lib', 'website-builder');
const PATHS_DIR = path.join(OUT_DIR, 'brand-icon-paths');

/** First char of slug → shard bucket; digits collapse into one `_digit` shard.
 *  MUST stay in lockstep with `brandShardKey` emitted into loaders.ts below. */
function bucketFor(slug: string): string {
  const c = slug.charAt(0);
  return c >= '0' && c <= '9' ? '_digit' : c;
}

const GEN_HEADER =
  '/**\n' +
  ' * AUTO-GENERATED by scripts/gen-brand-icons.ts — DO NOT EDIT BY HAND.\n' +
  ' * Regenerate: npx tsx scripts/gen-brand-icons.ts\n' +
  ' */\n\n';

// --- 1. Metadata list ------------------------------------------------------
const sortedMeta = [...iconsData].sort((a, b) =>
  a.title.localeCompare(b.title, 'en'),
);

let metaOut = GEN_HEADER;
metaOut +=
  '/** Lightweight brand-icon metadata. NO svg path data — see brand-icon-paths/. */\n';
metaOut += 'export interface BrandIconMeta {\n';
metaOut += '  /** simple-icons slug, e.g. `github`. Stored/selected as `si:<slug>`. */\n';
metaOut += '  slug: string;\n';
metaOut += '  /** Display title, e.g. `GitHub`. */\n';
metaOut += '  title: string;\n';
metaOut += "  /** Brand hex colour WITHOUT a leading '#', e.g. `181717`. */\n";
metaOut += '  hex: string;\n';
metaOut += '}\n\n';
metaOut += 'export const BRAND_ICONS: BrandIconMeta[] = [\n';
for (const m of sortedMeta) {
  metaOut += `  { slug: ${JSON.stringify(m.slug)}, title: ${JSON.stringify(
    m.title,
  )}, hex: ${JSON.stringify(m.hex)} },\n`;
}
metaOut += '];\n';
fs.writeFileSync(path.join(OUT_DIR, 'brand-icons.ts'), metaOut, 'utf8');

// --- 2. Sharded path maps --------------------------------------------------
if (!fs.existsSync(PATHS_DIR)) {
  fs.mkdirSync(PATHS_DIR, { recursive: true });
}

const buckets = new Map<string, Array<{ slug: string; path: string }>>();
let missing = 0;
for (const m of iconsData) {
  const entry = si[slugToVariableName(m.slug)];
  if (!entry || typeof entry.path !== 'string') {
    missing++;
    continue;
  }
  const b = bucketFor(m.slug);
  const list = buckets.get(b) ?? [];
  list.push({ slug: m.slug, path: entry.path });
  buckets.set(b, list);
}

const bucketKeys = [...buckets.keys()].sort();
for (const b of bucketKeys) {
  const list = (buckets.get(b) ?? []).sort((x, y) => x.slug.localeCompare(y.slug));
  let out = GEN_HEADER;
  out += `/** Brand svg path data for slugs starting with "${b}". Lazy-loaded only. */\n`;
  out += 'export const BRAND_PATHS: Record<string, string> = {\n';
  for (const { slug, path: d } of list) {
    out += `  ${JSON.stringify(slug)}: ${JSON.stringify(d)},\n`;
  }
  out += '};\n';
  fs.writeFileSync(path.join(PATHS_DIR, `${b}.ts`), out, 'utf8');
}

// --- 3. Loader map ---------------------------------------------------------
let loaders = GEN_HEADER;
loaders +=
  '/** Shape of a lazily-loaded brand-path shard module. */\n';
loaders += 'export interface BrandPathModule {\n';
loaders += '  BRAND_PATHS: Record<string, string>;\n';
loaders += '}\n\n';
loaders +=
  '/**\n' +
  ' * Lazy per-shard loaders. Each value is a `() => import()` thunk, so webpack\n' +
  ' * code-splits every shard into its own async chunk — none are in the live\n' +
  ' * page bundle until a brand icon in that shard actually renders.\n' +
  ' */\n';
loaders +=
  'export const BRAND_SHARD_LOADERS: Record<string, () => Promise<BrandPathModule>> = {\n';
for (const b of bucketKeys) {
  loaders += `  ${JSON.stringify(b)}: () => import(${JSON.stringify(`./${b}`)}),\n`;
}
loaders += '};\n\n';
loaders +=
  '/** Map a simple-icons slug to its shard key. Mirrors the generator buckets. */\n';
loaders += 'export function brandShardKey(slug: string): string {\n';
loaders += '  const c = slug.charAt(0);\n';
loaders += "  return c >= '0' && c <= '9' ? '_digit' : c;\n";
loaders += '}\n';
fs.writeFileSync(path.join(PATHS_DIR, 'loaders.ts'), loaders, 'utf8');

console.info(
  `[gen-brand-icons] wrote ${sortedMeta.length} brands across ${bucketKeys.length} shards (${missing} skipped for missing path).`,
);
